using UnityEngine;
using System.Collections;

public enum PLAYER_STATUS {  SALLY_ENTER ,SALLY_WAIT, RUNNER, FLASHBACK, FATHER_ENTER ,FATHER_WAIT, CAM_TO_FATHER ,GUARDIAN, SALLY_EXIT ,STAGE_CHG_SALLY, STAGE_CHG_FATHER, SALLY_CRASH, END };

public enum TAP_STATUS { JUMP, HOLD };

public enum OBJECT_ID { RUNNER, GUARDIAN, BOX, FLOOR, R_BOX, G_BOX, HOLDINGBOX, R_DOOR, G_DOOR, G_SWITCH, R_SWITCH, Timeball, MOVEORDER, TEXTFLOAT ,GOAL, SPIKE, SPRING, PORTAL, PHOTO, TOP_DECO, INTERACTION_PROP,END };

public enum SAVE_FORM { STG, TXT };

public enum SOUND_LIST { BUTTON_OFF, BUTTON_ON, CHG_CHAR, FATHER_ENTER, FATHER_EXIT, SALLY_DIE, GET_PHOTO ,GET_KEY_FIRST, GET_KEY, SPRING_SIDE ,SPRING_UP , EAT_TIMECAPSULE, END };

public enum UI_SOUND_LIST { ALBUM, BUTTON_ENTER, BUTTON_ERROR, BUTTON_EXIT, CLOTH_SELECT, FADE_IN, FADE_OUT, PICTURE_MOVE, TEXT_IN, TEXT_OUT, END };

public enum SOUND_INTERACTION { CROW_00, CROW_01, CROW_02, DOVE, LIGHT, SIGNAL_LIGHT, SPARROW, WOOD_SIGN, END };

public enum MainUIStatus { MAIN, CHAR_MOVING ,WORLD, STAGE, OPTION, CREDIT, LANGUAGE, PHOTO, REALLY_BUY, RESTORE, RESTORE_CHECK, REALLY_QUIT, CONTROL, END };

public enum TEXT_FLOAT { SALLY, FATHER, MEMORY, END };

public enum SPRING_DIR { UP, LEFT, RIGHT };

public enum CAM_TUTORIAL { ZOOMED, ZOOMING, ZOOM_OUT, NOT_TUTORIAL };

public enum CURSOR_WORLD_STATE { PHOTO, CHPT1, CHPT2, CHPT3, CHPT4, CHPT5, OPTION };

public enum CURSOR_STAGE_STATE { STAGE1, STAGE2, STAGE3, STAGE4, STAGE5, STAGE6 };

public enum CURSOR_OPTION_STATE { SOUND, MUSIC, RESOLUTION, SCREEN_MODE, LANGUAGE, CONTROL, CREDIT };

public enum FontType
{
	SystemFont,
	Londrina,
	Jua,
	GenJyuu,
	END
}